journal_app/app/journal/forms.py
from datetime import datetime, timezone
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileRequired, FileAllowed
from werkzeug.utils import secure_filename
from wtforms import StringField, BooleanField, SubmitField, TextAreaField
from wtforms.validators import DataRequired, ValidationError, EqualTo, Length
from flask import render_template, flash, redirect, url_for, request, current_app
from flask_login import current_user, login_required
import sqlalchemy as sa
from app import db
from app.models import User, JournalEntry, JournalEntryTag, Tag, Media
from app.journal import bp

""" Journal Forms - currently the same for edit and new journal entry """
class JournalEntryForm(FlaskForm):
    title = StringField(('Title'), validators=[DataRequired()])
    media_file = FileField('Media File', validators=[FileAllowed(['jpg', 'png', 'jpeg', 'gif', 'mp4'])])
    content = TextAreaField('Content', validators=[DataRequired()])
    tags = StringField('Tags (comma-separated)')#, render_kw={'readonly': True})
    submit = SubmitField('Save')

class EditJournalEntryForm(FlaskForm):
    title = StringField(('Title'), validators=[DataRequired()])
    media_file = FileField()
    content = TextAreaField('Content', validators=[DataRequired()])
    tags = StringField('Tags (comma-separated)')#, render_kw={'readonly': True})
    submit = SubmitField('Save')

journal_app/app/journal/__init__.py
from flask import Blueprint

bp = Blueprint('journal', __name__)

from app.journal import routes

journal_app/app/journal/routes.py
from flask import Flask, request, redirect, current_app, render_template, flash, url_for, abort, send_from_directory
from config import Config
from flask_login import current_user, login_required, LoginManager
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
import logging
from logging.handlers import SMTPHandler, RotatingFileHandler
import os
from app import db
import sqlalchemy as sa 
from app.models import User, JournalEntry, Media, Tag, JournalEntryTag, JournalEntryMedia
from app.journal.forms import JournalEntryForm, EditJournalEntryForm
from app.journal import bp
import datetime as dt
import pandas as pd
from werkzeug.utils import secure_filename
from pathlib import Path
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileRequired
import datetime as dt
import pandas as pd
import json
from app.tags_generation.tags_generation import tags_generator


""" Route for displaying a user's journal entries. This also passes
    journal entry ids to the edit hyperlink allowing for a signed in
    user to edit an existing journal entry. Currently shows all 
    user journal entries in one page, which can be cumbersome.
    TODO: Add pagination, let user select how many entries to 
    show at one time.
"""
@bp.route('/journal/', methods=['GET', 'POST'])
@login_required
def journal():

    # Checks if user has created their first journal entry
    # this helps prevent errors when trying to display a journal page
    # with no journal entries
    test_entry_exists()
    
    entries = JournalEntry.query.filter_by(user_id=current_user.user_id).order_by(JournalEntry.entry_published.desc()).all()

    journal_entries = []
    for entry in entries:
        tags = [tag.tag_name for tag in entry.tags]
        journal_entry = {}
        the_key = str(entry.entry_id)

        journal_entry[the_key] = {
            'title': entry.entry_title,
            'date': pd.to_datetime(entry.entry_published),
            'image_path': ['blank', entry.media_id][0 if entry.media_id is None else 1],
            'content': entry.entry_body,
            'tags': tags.copy()
        }
        #flash(tags_generator(entry.entry_body))
        if journal_entry[the_key]['image_path'] != 'blank':
            media_file_info = db.first_or_404(sa.select(Media).where(Media.media_id == entry.media_id))
                    
            if media_file_info.media_format in ['jpg', 'png', 'gif', '.jpg', '.png', '.gif']:

                journal_entry[the_key]['image_path'] = media_file_info.media_file_path


        journal_entries.append(journal_entry.copy())

    if len(journal_entries) == 0:
        journal_entries.append({'one':{'title': 'your title here', 'date': 'when created?', 'content': 'what would you write?'}})
        journal_entries.append({'two':{'title': 'your title here', 'date': 'when created?', 'content': 'what would you write?'}})
        flash('You have no journal entries yet! Perhaps you should create one now..')

    return render_template('journal/journal.html', journal_entries=journal_entries)



""" Route for new journal entry. Title, Body, File attachment, and 
    Tag generation of body supported. Audio transcription implementation
    did not make it into this version due to current interface constraints.
    Tag field supports user entered tags or auto generated tags. Currently,
    user can add tag generations without using the zero shot tagging 
    functionality, or add them into addition to auto Tag generation.
    TODO (both new and edit): Markup implementaiton for journal entries,
    allowing for HTML / CSS element rendering (bold, italics, font, color, etc.)
"""
@bp.route('/new_entry', methods=['GET', 'POST'])
@login_required
def new_entry():
    form = JournalEntryForm()

    if request.method == 'POST' and form.validate_on_submit():
        new_entry = JournalEntry(
            user_id = current_user.user_id,            
            entry_title=form.title.data,
            media_id=None,
            entry_body=form.content.data
        )
        
        db.session.add(new_entry)
        db.session.flush()

        tags_str = form.tags.data
        new_entry.tags = list()
        my_tags = list()
        if tags_str:
            tags_list = [tag.strip() for tag in tags_str.split(',')]
            for tag_name in tags_list:
                if tag_name:
                    tag = db.session.scalar(sa.select(Tag).where(Tag.tag_name == tag_name))
                    if not tag:
                        tag = Tag(tag_name=tag_name)
                        db.session.add(tag)
                        db.session.commit()
                    new_entry.tags.append(tag)

        db.session.add(new_entry)
        db.session.commit()


        file = request.files['media_file']
        if file.filename != '':
            if upload_file(file, new_entry) is None:
                flash("it's none")
                return render_template('journal/new_entry.html', form=form)

        
        return redirect(url_for('journal.journal'))    
    else:
        return render_template('journal/new_entry.html', form=form)


def test_entry_exists():
    tst = JournalEntry.query.filter_by(user_id=current_user.user_id).first_or_404()
    if tst.entry_id is None:
        flash('no entries yet!')
        return(render_template('/index.html'))

""" Route to handle auto-Tag generation duties """
@bp.route('/generate_entry_tags', methods=['POST'])
@login_required
def generate_entry_tags():
    data = request.get_json()
    content = data.get('content', '')
    generated_tags = tags_generator(content)
    return json.dumps({'tags': generated_tags})


""" Handles uploading files. Uploaded files permitted include
    jpg, jpeg, png, gif, mp4, mp3, and avi. There is currently 
    a 32MB file size cap. Files are stored by username (directory).
    Further refinements should include purging old files no longer
    displayed or linked to a user's journal entry. File attribute
    checking (same filename, different files) are in the queue to
    implement. This route also utilized secure_filename checking
    to make shell injections more difficult.
"""
@bp.route('/new_entry', methods=['POST'])
@login_required
def upload_file(f_path, jrnl_entry, new_entry=True):
    filename = secure_filename(f_path.filename)
    filename = filename.lower()
    if filename != '':
        
        ### organize directories
        target_dir = 'app/static/uploads/{}'.format(current_user.username)
        if not os.path.exists(target_dir):
            os.mkdir(target_dir)
        
        file_ext = os.path.splitext(filename)[1]
        
        # NEED TO UPDATE THIS AND NEW_ENTRY?
        if file_ext not in current_app.config['ALLOWED_EXTENSIONS']:
            flash('{}: file type unsupported'.format(file_ext))
            return None

        elif new_entry:
            mf_path  = os.path.join(target_dir, filename)

            new_media_item = Media(
                media_file_path = mf_path,
                media_format = file_ext
            )

            f_path.save(mf_path)

            db.session.add(new_media_item)
            db.session.commit()

            db.session.add(jrnl_entry)
            jrnl_entry.media_id = new_media_item.media_id
            db.session.commit()
            return 0
        
        else:
            mf_path  = os.path.join(target_dir, filename)
            f_path.save(mf_path)

            return mf_path


""" Edit entry supports changing the title, body, image, or tags of 
    a post that has already been submitted. Edit entry essentially has
    all of the functionality of new journal entries, just over the top
    of an existing journal entry.
    
    It isn't possible to show anything other than 'No File Chosen' in the form field.
    Options to demosntrate there is a file there:
        1. Include a thumbnail under the Choose FileField
        2. Display text with the filename below it
        3. ??
"""
@bp.route('/edit_entry/<int:entry_id>', methods=['GET', 'POST'])
@login_required
def edit_entry(entry_id=None, media_id=None):    
    form = EditJournalEntryForm(enctype="multipart/form-data")
    m_id = None
    upload_success = False
    
    if request.method == 'POST' and form.validate_on_submit():
        upd_entry = db.first_or_404(sa.select(JournalEntry)
            .where(JournalEntry.entry_id == entry_id and JournalEntry.user_id == current_user.user_id))


        upd_entry.entry_title=form.title.data
        upd_entry.entry_body=form.content.data
        db.session.add(upd_entry)
        db.session.commit()
          
        tags_str = form.tags.data
        if tags_str:
            new_tags = list()
            tags_list = [tag.strip() for tag in tags_str.split(',')]
            for tag_name in tags_list:
                if tag_name:
                    tag = db.session.scalar(sa.select(Tag).distinct().where(Tag.tag_name == tag_name))
                    if not tag:
                        tag = Tag(tag_name=tag_name)
                        db.session.add(tag)
                        db.session.commit()
                    if tag_name is not None and tag is not '':
                        new_tags.append(tag)
     
            upd_entry = db.first_or_404(sa.select(JournalEntry)
                 .where(JournalEntry.entry_id == entry_id and JournalEntry.user_id == current_user.user_id))  
            upd_entry.tags = []
            for t in new_tags:
                upd_entry.tags.append(t)
            db.session.commit()


        if upd_entry.media_id is not None:
            m_id = db.first_or_404(sa.select(Media).where(Media.media_id == upd_entry.media_id))


        file = request.files['media_file']
        if file.filename != '':
            if m_id is not None:
                og_fpath = m_id.media_file_path
                og_fname = og_fpath.split('/')[-1]

                if og_fname != file.filename:

journal_app/app/templates/journal/edit_entry.html
{% extends "base.html" %}
{% block body_class %}paper-page{% endblock %}
{% import "bootstrap_wtf.html" as wtf %}

{% block content %}
    <h1 class="entry-title">Edit Journal Entry</h1>
    <form method="POST" enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        {{ wtf.form_field_edit(form.title) }}
        {{ wtf.form_field_edit(form.media_file) }}
        {{ wtf.form_field_edit(form.content) }}
        {{ wtf.form_field_edit(form.tags) }}   
        <div class="d-flex justify-content-between align-items-center mt-4"><p style="color:dodgerblue;margin-bottom:-5%;margin-top:-5%;" id="running-notice"></p></div>
        <div class="d-flex justify-content-between align-items-center mt-4">            
            <tr>
                <td scope="col">
                    <span class="me-2 fw-semibold" style='float:right;margin-top:3.5%;margin-bottom:3%;margin-left:22%;margin-right:-25%'>Try our AI Features:</span>
                </td>
                <td scope="col">
                    <span class="me-2 fw-semibold" style='float:right;margin-top:5%;margin-bottom:5%;margin-left:-10%;'></span>
                </td>
            </tr>
            <tr>
                <td scope='col'>
                    <button type="button" id="generate_tags" class="btn btn-outline-primary" style='float:right; margin-right:8%;margin-left:-5%;'>
                        Generate Tags
                    </button>
                </td>
                <td scope="col">
                    <button type="submit" id='submit' class="btn btn-outline-primary" style='float:right; margin-right:2%;width:15%;'>Save</button>
                </td>                               
            </tr>
        </div>
    </form>
    
{% endblock %}

{% block scripts %}
{{ super() }}
<script>
        document.addEventListener('DOMContentLoaded', function() {
            const generateTagsButton = document.getElementById('generate_tags');
            const contentField = document.getElementById('content'); 
            const tagsField = document.getElementById('tags');
            const runningMssg = document.getElementById('running-notice')

            if (generateTagsButton && contentField && tagsField) {
                generateTagsButton.addEventListener('click', function() {
                    runningMssg.innerText = 'Generating Tags';
                    setInterval(changeText, 1800);
                    const content = contentField.value;
                    fetch('/journal/generate_entry_tags', {
                        method: 'POST',
                        headers: {
                            'Content-Type': 'application/json'
                        },
                        body: JSON.stringify({ 'content': content })
                    })
                    .then(response => response.json())
                    .then(data => {
                        if (data && data.tags) {
                            tagsField.value = data.tags.join(', ');
                            runningMssg.innerText = 'Tags generated!';
                            setTimeout(hideText, 4000);
                        } else {
                            runningMssg.innerText = 'error - unspecified';
                        }
                    });
                });
            }
        });
        let countDots = 0;
        function changeText() {
            let cycleMssg = document.getElementById('running-notice');
            if (cycleMssg.innerText != '' && cycleMssg.innerText != 'Tags generated!') {
                let dotCount = countDots++ % 3;
                let dots = ['.', '..', '...'];
                const baseText = 'Generating Tags';
                cycleMssg.innerText = baseText + dots[dotCount];
            }           
        }
        function hideText() {
            document.getElementById('running-notice').innerText = '';
        }
    </script>
{% endblock %}

journal_app/app/templates/journal/journal.html
{% extends "base.html" %}
{% block body_class %}paper-page{% endblock %}
{% import "bootstrap_wtf.html" as wtf %}

{% block content %}
<h1 class="text-center my-4 entry-title">My Journal</h1>

<div class="container">

    {% for journal_entry in journal_entries %}
        {% for item, entry in journal_entry.items() %}
            <div class="card p-4 mb-4 shadow-sm">
                <h4>{{ entry.title }}</h4>
                <small class="text-muted">Published on: {{ entry.date.strftime('%B %d, %Y at %I:%M %p') }}</small>

                {% if entry.image_name != 'blank' %}
                    {% set filePath = entry.image_path.replace('app/static/', '').replace('\\', '/') %}
                    {% set fullPath = url_for('static', filename=filePath) %}
                    {% if fullPath != '/app/static/blank' %}
                        <div class="my-3">
                            <img src="{{ fullPath }}" alt="Journal Image" class="img-fluid rounded" style="max-width: 70%;">
                        </div>
                    {% endif %}
                {% endif %}

                <div class="mt-3">
                    {% for line in entry.content.split('\n') %}
                        <p>{{ line }}</p>
                    {% endfor %}
                </div>

                {% if entry.get('tags') %}
                    <p class="mt-3">
                        Tags:
                        {% for tag in entry.tags %}
                            <span class="badge bg-secondary">{{ tag }}</span>
                        {% endfor %}
                    </p>
                {% endif %}

                <div class="d-flex justify-content-end mt-3">
                    <a href="{{ url_for('journal.edit_entry', entry_id=item) }}" class="btn btn-sm btn-outline-primary">Edit</a>
                </div>
            </div>
        {% endfor %}
    {% endfor %}
    <div class="d-flex justify-content-between align-items-center mt-4" style="float:right;margin-bottom:3%;">
        <button type="button" class="btn btn-outline-primary" id="downloadBtn" style="width:100%;background-color:goldenrod;" onclick="getPdf()">
            Save as PDF
        </button><br>
    </div>
</div>
<script>
    function getPdf() {
        window.print()
    }
</script>
{% endblock %}

journal_app/app/templates/journal/new_entry.html
{% extends "base.html" %}
{% block body_class %}paper-page{% endblock %}
{% import "bootstrap_wtf.html" as wtf %}

{% block content %}
    <h1 class="entry-title">New Journal Entry</h1>
    <form method="POST" enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        {{ wtf.form_field_edit(form.title) }}
        {{ wtf.form_field_edit(form.media_file) }}
        {{ wtf.form_field_edit(form.content) }}
        {{ wtf.form_field_edit(form.tags) }}   
        <div class="d-flex justify-content-between align-items-center mt-4"><p style="color:dodgerblue;margin-bottom:-5%;margin-top:-5%;" id="running-notice"></p></div>
        <div class="d-flex justify-content-between align-items-center mt-4">    
            <tr>
                <td scope="col">
                    <span class="me-2 fw-semibold" style='float:right;margin-top:3.5%;margin-bottom:3%;margin-left:22%;margin-right:-25%'>Try our AI Features:</span>
                </td>
                <td scope="col">
                    <span class="me-2 fw-semibold" style='float:right;margin-top:5%;margin-bottom:5%;margin-left:-10%;'></span>
                </td>
            </tr>
            <tr>
                <td scope='col'>
                    <button type="button" id="generate_tags" class="btn btn-outline-primary" style='float:right; margin-right:8%;margin-left:-5%;'>
                        Generate Tags
                    </button>
                </td>
                <td scope="col">
                    <button type="submit" id='submit' class="btn btn-outline-primary" style='float:right; margin-right:2%;width:15%;'>Save</button>
                </td>                               
            </tr>
        </div>
    </form>
    
{% endblock %}

{% block scripts %}
    {{ super() }}
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            const generateTagsButton = document.getElementById('generate_tags');
            const contentField = document.getElementById('content'); 
            const tagsField = document.getElementById('tags');
            const runningMssg = document.getElementById('running-notice')

            if (generateTagsButton && contentField && tagsField) {
                generateTagsButton.addEventListener('click', function() {
                    runningMssg.innerText = 'Generating Tags';
                    setInterval(changeText, 1800);
                    const content = contentField.value;
                    fetch('/journal/generate_entry_tags', {
                        method: 'POST',
                        headers: {
                            'Content-Type': 'application/json'
                        },
                        body: JSON.stringify({ 'content': content })
                    })
                    .then(response => response.json())
                    .then(data => {
                        if (data && data.tags) {
                            tagsField.value = data.tags.join(', ');
                            runningMssg.innerText = 'Tags generated!';
                            setTimeout(hideText, 4000);
                        } else {
                            runningMssg.innerText = 'error - unspecified';
                        }
                    });
                });
            }
        });
        let countDots = 0;
        function changeText() {
            let cycleMssg = document.getElementById('running-notice');
            if (cycleMssg.innerText != '' && cycleMssg.innerText != 'Tags generated!') {
                let dotCount = countDots++ % 3;
                let dots = ['.', '..', '...'];
                const baseText = 'Generating Tags';
                cycleMssg.innerText = baseText + dots[dotCount];
            }           
        }
        function hideText() {
            document.getElementById('running-notice').innerText = '';
        }
    </script>
{% endblock %}